
name: Pantheon Deploy
on:
  push:
    branches:
      - 'main'
      - 'master'
      - 'qa'
      - 'integration'
      - 'security'
      - 'hotfix'
      - 'alpha'
      - 'beta'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup and Build
        uses: taoti/actions-build@main
        with:
          dir_theme: web/themes/custom/_theme_name_
          secret_token_gh: ${{ secrets.TOKEN_GH }}
      - name: Pantheon deploy
        uses: taoti/actions-pantheon@main
        with:
          secret_ssh_key: ${{ secrets.PANTHEON_SSH_KEY }}
          secret_terminus_token: ${{ secrets.PANTHEON_TERMINUS_TOKEN }}
          site_name: _site_name_
