#!/bin/bash
set -eo pipefail

if [[ ${GITHUB_REF_NAME} == 'main' ]] ; then
  DEFAULT_ENV='dev'
elif [[ ${GITHUB_REF_NAME} == 'master' ]] ; then
  DEFAULT_ENV='dev'
else
  DEFAULT_ENV=$GITHUB_REF_NAME
fi
(
  echo "DEFAULT_ENV=$DEFAULT_ENV"
  echo "TERMINUS_ENV=$DEFAULT_ENV"
) >> $GITHUB_ENV

if [[ -x "$GITHUB_WORKSPACE/set-environment" ]] ; then
  echo "running 17"
  "$GITHUB_WORKSPACE/set-environment"
else
  echo "running 20"
  ls -all ../../../work
  echo "running 22"
  ls -all ../../
  echo "running 24"
  ls -all ../
  ls "$GITHUB_WORKSPACE"
  (
    echo "THEME_DIR=web/themes/$SECRET_SITE_NAME"
    echo "NPM_VER=12.x"
    echo "PHP_VER=7.4"
  ) >> $GITHUB_ENV
fi
